name: qrmenu
description: A production-ready QR Menu app for customers to scan QR codes and order food.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # QR Code Scanner
  qr_code_scanner: ^1.0.1
  permission_handler: ^12.0.1
  
  # State Management
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # HTTP & JSON
  http: ^1.1.0
  dio: ^5.3.3
  json_annotation: ^4.9.0
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.1.0
  badges: ^3.1.2
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.1.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.2.1
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  
  # Firebase
  firebase_core: ^4.2.0
  firebase_core_web: ^3.2.0
  firebase_auth: ^6.1.1
  firebase_auth_web: ^6.0.4
  cloud_firestore: ^6.0.3
  cloud_firestore_web: ^5.0.3
  
  # Scanner
  mobile_scanner: ^7.1.2
  go_router: ^16.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  fake_cloud_firestore: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/mock_data/
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
